using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace translator
{
    class Program
    {
       static string  eol1 = Environment.NewLine;
       static string eol2 = "";
        static string nameTranslate = "nSysTranslationInfo";
        static void Main(string[] args)
        {
            int ilosctlumaczeni = args.Length - 1;
            eol2 = eol1 + eol1;
            StringBuilder sb = new StringBuilder();

            string root = args[0];
            Localization l = new Localization();
            l.LocalizationUi = new List<Item>();

            sb.Append("deklararacja nSysTranslationInfo1" + eol2);

            for (int i = 1; i<=ilosctlumaczeni; i++)
            {
                sb.Append("Lsi.Nvm.Lib.nSys.Translation.NSysTranslationInfo "+nameTranslate + (i+1) + " = new Lsi.Nvm.Lib.nSys.Translation.NSysTranslationInfo();" + eol1);
            }
            for (int i = 1; i <=ilosctlumaczeni; i++)
            {
                Item ii = new Item(root,args[i],"Caption","tr_"+args[i]);
                l.LocalizationUi.Add(ii);
            }



            string tlumaczenie=l.Serialize<Localization>();
            sb.Append(eol2+"tlumaczenie dla en"+eol1);
            sb.Append(tlumaczenie);


            sb.Append(eol2 + "definiowanie nSysTranslationInfo1 " + eol1);

            for (int i = 1; i <= ilosctlumaczeni; i++)
            {
                sb.Append(defTranslate(i,root,args[i]));
                sb.Append("this.nSysTranslator.Translations.Add("+nameTranslate+(i+1)+");" + eol1);
                sb.Append(eol1);
            }

           

            File.WriteAllText("wynik.txt", sb.ToString());
            System.Windows.Forms.MessageBox.Show("Test");

        }

        private static string defTranslate(int i,string rooot,string name)
        {
            string naglowek = nameTranslate + (i+1);
            string result=naglowek+".AutoGenerated = true;"+eol1;
            result += naglowek+ ".Default = \"domyslnetlumaczenie " + name + "\";" + eol1;
            result += naglowek + ".Description = \"\";" + eol1;
            result += naglowek+ ".Name = \""+name+"\";" + eol1;
            result += naglowek + ".Property = \"Caption\";" + eol1;
            result += naglowek + ".Root = \""+rooot+"\"; " + eol1;


                /*
            nSysTranslationInfo1.Root = "Lsi.Nvm.App.NPosManager.WinLogic.UserControls.Kasa.KasaRejestrLokaluRaportKasowyZ" +
  "estawienieGridPresenter";
                 */
            return result;
        }
    }
}
